unit TestRoomerBookingCommunicationModel_RequestsResponses;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, RoomerFinancialDataModel_ModelObjects, XMLIntf,
  RoomerBookingCommunicationModel_RequestsResponses, uRoomerSchema, Classes,
  SysUtils, OXmlPDOM, Spring.Collections.Lists, Spring.Collections;

type
  // Test methods for class TxsdInvoiceResponse

  TestTxsdInvoiceResponse = class(TTestCase)
  strict private
    FSUT: TxsdInvoiceResponse;
  private
    procedure LoadSUTFromXML(const filename: string);
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSetuptearDown;
    procedure TestLoadInvoiceResponseXML;
    procedure TestLoadComplexInvoiceResponseXML;
    procedure TestLoadComplexInvoiceResponseWithDiscountsXML;
    procedure TestLoadComplexInvoiceResponseWithTaxesXML;
  end;

implementation

uses
  Math
  , uRoomerCanonicalDataModel_SimpleTypes;

procedure TestTxsdInvoiceResponse.SetUp;
begin
  FSUT := TxsdInvoiceResponse.Create;
end;

procedure TestTxsdInvoiceResponse.TearDown;
begin
  FSUT.Free;
end;

procedure TestTxsdInvoiceResponse.LoadSUTFromXML(const filename: string);
var
  xmlDoc: IXMLDocument;
begin
  xmlDoc := TXMLDocument.Create;
  xmlDoc.LoadFromFile(filename);

  CheckFalse(Assigned(xmlDoc.ParseError), 'Errors during parsing of XML file');

  FSUT.SetPropertiesFromXMLNode(xmlDoc.DocumentElement.FirstChild);
end;

procedure TestTxsdInvoiceResponse.TestLoadComplexInvoiceResponseWithDiscountsXML;
const
  cResponseFile = '..\..\XMLData\InvoiceResponseWithDiscount.xml';
begin
  LoadSUTFromXML(cResponseFile);
  CheckEquals(1, FSUT.Count);
  CheckEquals('22822', FSUT.Items[0].RoomReservation);
  CheckEquals(9 , FSUT.Items[0].LineItemList.Count);

  // Check on a discount lineitem
  CheckIs(FSUT.Items[0].LineItemList[7].Item, TxsdDiscountBillableEntryType);
  CheckEquals('GBP', TxsdDiscountBillableEntryType(FSUT.Items[0].LineItemList[7].Item).UnitPrice.Currency.AsString);
  CheckTrue(SameValue(8.69565217, TxsdDiscountBillableEntryType(FSUT.Items[0].LineItemList[7].Item).UnitPrice.Amount));

end;

procedure TestTxsdInvoiceResponse.TestLoadComplexInvoiceResponseWithTaxesXML;
const
  cResponseFile = '..\..\XMLData\InvoiceResponseWithDiscount.xml';
var
  sum: double;
  taxList: TxsdApplicableTaxesList;
  tax: TxsdApplicableTax;
begin
  LoadSUTFromXML(cResponseFile);

  // Check taxes
  CheckIs(FSUT.Items[0].LineItemList[0].Item, TxsdExtendedBillableEntryType);

  taxList := TxsdExtendedBillableEntryType(FSUT.Items[0].LineItemList[0].Item).ApplicableTaxList;
  CheckEquals(3, taxList.Count);
  sum := 0.0;
  for tax in taxList do
    sum := sum + tax.Amount.Amount;

  CheckTrue(SameValue(16.1771945, sum));
end;

procedure TestTxsdInvoiceResponse.TestLoadComplexInvoiceResponseXML;
const
  cResponseFile = '..\..\XMLData\InvoiceResponseComplex.xml';
begin
  LoadSUTFromXML(cResponseFile);

  CheckEquals(1, FSUT.Count);
  CheckEquals('2589', FSUT.Items[0].Reservation);
  CheckEquals(4 , FSUT.Items[0].LineItemList.Count);

  CheckEquals('Booking Button',  FSUT.Items[0].GuestData.Name);
  CheckEquals('Raupplaan 20',  FSut.items[0].GuestData.Address.Address);
  CheckEquals('NL', FSut.items[0].GuestData.Address.Country.AsString);

  checkEquals('EUR', FSut.items[0].CurrencyData.InvoiceCurrency.AsString);
  checkEquals('EUR', FSut.items[0].CurrencyData.ConversionFromHotelCurrency.From.AsString);
  checkEquals('EUR', FSut.items[0].CurrencyData.ConversionFromHotelCurrency.To_.AsString);
  checkTrue(SameValue(1.0, FSut.items[0].CurrencyData.ConversionFromHotelCurrency.Factor));

end;

procedure TestTxsdInvoiceResponse.TestLoadInvoiceResponseXML;
const
  cInvoiceResponseFile = '..\..\XMLData\InvoiceResponse.xml';
begin
  LoadSUTFromXML(cInvoiceResponseFile);

  CheckEquals(1, FSUT.Count);
  CheckEquals('2060', FSUT.Items[0].Reservation);
  CheckEquals(1 , FSUT.Items[0].LineItemList.Count);
  CheckEquals(TxsdExtendedBillableEntryType.Classname , FSUT.Items[0].LineItemList[0].Item.Classname);
  CheckTrue(SameValue(188.6792453 , TxsdExtendedBillableEntryType(FSUT.Items[0].LineItemList[0].Item).TotalPaymentPriceGross.Amount));

  CheckEquals('GUEST-NL' , FSUT.Items[0].CustomerData.Customer);
  CheckEquals('Bjorn Heidarr Gudmundsson' , FSUT.Items[0].GuestData.Name);
  CheckEquals('EUR' , FSUT.Items[0].CurrencyData.InvoiceCurrency.asString);
  CheckEquals('EUR' , FSUT.Items[0].CurrencyData.ConversionFromHotelCurrency.From.AsString);
  CheckEquals('EUR' , FSUT.Items[0].CurrencyData.ConversionFromHotelCurrency.To_.AsString);
  CheckTrue(SameValue(160 , FSUT.Items[0].CurrencyData.ConversionFromHotelCurrency.Factor));



end;

procedure TestTxsdInvoiceResponse.TestSetuptearDown;
begin
  Check(True);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTxsdInvoiceResponse.Suite);
end.

